# Generated by Django 5.2.8 on 2025-11-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
